#ifndef _POTENTIOMETER_CONFIG_H_ 
#define _POTENTIOMETER_CONFIG_H_ 

/*******************************************************/
/**************** Public Definitions *******************/
/*******************************************************/
/*Comment!: Number of Connected Switches */
/*Range!  : POTENTIOMETER_u8NUM1 : POTENTIOMETER_u8NUM8 */
#define POTENTIOMETER_CONNECTED_NUM	 POTENTIOMETER_u8NUM1

/*Comment!: POTENTIOMETER Initial State*/
/*Range!  : POTENTIOMETER_u8ENABLE or POTENTIOMETER_u8DISABLE */
#define POTENTIOMETER_u8NUM1STATE		POTENTIOMETER_u8ENABLE
#define POTENTIOMETER_u8NUM2STATE		POTENTIOMETER_u8DISABLE
#define POTENTIOMETER_u8NUM3STATE		POTENTIOMETER_u8DISABLE
#define POTENTIOMETER_u8NUM4STATE		POTENTIOMETER_u8DISABLE
#define POTENTIOMETER_u8NUM5STATE		POTENTIOMETER_u8DISABLE
#define POTENTIOMETER_u8NUM6STATE		POTENTIOMETER_u8DISABLE
#define POTENTIOMETER_u8NUM7STATE		POTENTIOMETER_u8DISABLE
#define POTENTIOMETER_u8NUM8STATE		POTENTIOMETER_u8DISABLE

/*Comment!: POTENTIOMETER Channel Configuration*/
/*Range!  : ADC_u8CH0 or ADC_u8CH7 */
#define POTENTIOMETER_u8NUM1CH		ADC_u8CH0
#define POTENTIOMETER_u8NUM2CH		ADC_u8CH0
#define POTENTIOMETER_u8NUM3CH		ADC_u8CH0
#define POTENTIOMETER_u8NUM4CH		ADC_u8CH0
#define POTENTIOMETER_u8NUM5CH		ADC_u8CH0
#define POTENTIOMETER_u8NUM6CH		ADC_u8CH0
#define POTENTIOMETER_u8NUM7CH		ADC_u8CH0
#define POTENTIOMETER_u8NUM8CH		ADC_u8CH0

#endif 
